import test from 'node:test';
import assert from 'node:assert/strict';
import {ID,ABILITIES} from '../scripts/rules.js';
let prompts=[],messages=[],actors=new Map(),sequence=0,rollCancelled=false,backups=[],hooks={};
const notifications=[];
function patch(obj,update){for(const [path,v]of Object.entries(update)){const keys=path.split('.');let o=obj;for(const k of keys.slice(0,-1))o=o[k]??={};o[keys.at(-1)]=v;}return obj;}
function doc(data){return {...data,async update(p){patch(this,p);return this;},getFlag(s,k){return this.flags?.[s]?.[k];},async setFlag(s,k,v){patch(this,{[`flags.${s}.${k}`]:v});return this;}};}
function actor(name,keys=[]){const a=doc({id:name,uuid:`Actor.${name}`,name,type:'super',isOwner:true,flags:{},items:keys.map(key=>({id:key,flags:{[ID]:{catalogueId:`starter:${key}`}},system:{roll:{bonus:0,edges:0,troubles:0}}})),effects:[],system:{rank:3,karma:0,lifepool:{health:{value:100,max:100},focus:{value:30,max:30}},abilities:Object.fromEntries(ABILITIES.map(k=>[k,{value:3,nonCombatScore:3,edges:0,troubles:0,damageMultiplier:3,damageModifier:3,defense:13}]))},toObject(){return JSON.parse(JSON.stringify({name:this.name,flags:this.flags,system:this.system,items:this.items,effects:this.effects}));},async createEmbeddedDocuments(type,entries){const output=entries.map(e=>({...e,id:`effect${++sequence}`}));this.effects.push(...output);return output;},async deleteEmbeddedDocuments(type,ids){this.effects=this.effects.filter(e=>!ids.includes(e.id));},async updateEmbeddedDocuments(type,changes){for(const c of changes){const i=this.items.find(i=>i.id===c._id);patch(i,c);}return this.items;}});actors.set(a.uuid,a);return a;}
class FakeRoll {
 constructor(_formula,_data,options){this.options=options;this.actor=options.actor;this.ability=options.ability;this.type=options.rollType;this.against=options.against;this.edges=options.edges;this.troubles=options.troubles;this.rerolls={history:[]};this.dice=[{}, {results:[{result:1,active:true}]}];this.template='native';this.finalResults={total:20};this.fantasticResult=true;this.ultimateFantasticResult=false;}
 get edgesAndTroubles(){return this.edges-this.troubles;}
 async evaluate(){return rollCancelled?null:this;}
 activeResultDie(){return {total:6};}
 prepareChatTemplateData(){return {};}
 toJSON(){return {total:this.finalResults.total,edges:this.edges,troubles:this.troubles};}
 async toMessage(data){return ChatMessage.create({...data,rolls:[this]});}
 async mvReroll(){this.rerolls.history.push('reroll');}
 async undoLastReroll(){this.rerolls.history.pop();}
}
globalThis.foundry={applications:{api:{ApplicationV2:class{},DialogV2:{prompt:async()=>prompts.shift(),confirm:async()=>prompts.shift()}},handlebars:{renderTemplate:async()=>'<p>Native roll</p>'}}};
globalThis.ChatMessage={getSpeaker:({actor})=>({alias:actor.name}),create:async data=>{const m=doc({id:`chat${++sequence}`,flags:{},...data});messages.push(m);return m;}};
globalThis.fromUuid=async uuid=>actors.get(uuid);
globalThis.Hooks={on:(name,fn)=>{hooks[name]=fn;}};
globalThis.ui={notifications:Object.fromEntries(['info','warn','error'].map(k=>[k,msg=>notifications.push(msg)]))};
globalThis.Actor={create:async data=>{const backup={name:data.name};backups.push(backup);return backup;}};
globalThis.Folder={create:async()=>({id:'recovery'})};
const {usePower,resolveAttack,abilityCheck,upgradeContent,registerActionHooks}=await import('../scripts/actions.js');
function setup(){prompts=[];messages=[];actors=new Map();rollCancelled=false;backups=[];hooks={};globalThis.game={user:{id:'gm',isGM:true,targets:new Set()},users:{activeGM:{id:'gm'}},mvrpg:{D616:FakeRoll},messages:{get:id=>messages.find(m=>m.id===id),get contents(){return messages;}},folders:[],combat:{id:'combat1',started:true,round:1,turn:0,turns:[]}};}
function target(a){game.user.targets=new Set([{actor:a}]);}
test('cancelled power costs no Focus and creates no effects',async()=>{setup();const a=actor('hero',['attack-stance']);prompts=[null];await usePower(a,'starter:attack-stance');assert.equal(a.effects.length,0);assert.equal(a.system.lifepool.focus.value,30);});
test('Attack Stance creates a native damage modifier and refuses stacking',async()=>{setup();const a=actor('hero',['attack-stance']);prompts=[{}];await usePower(a,'starter:attack-stance');assert.equal(a.effects[0].changes[0].key,'system.abilities.melee.damageModifierBonus');assert.equal(a.effects[0].changes[0].value,'@system.abilities.melee.value');await assert.rejects(usePower(a,'starter:attack-stance'),/already active/);});
test('Counterstrike spends Focus once and rounds half regular damage upward',async()=>{setup();const a=actor('hero',['attack-stance','counterstrike-technique']),t=actor('enemy');a.effects=[{flags:{[ID]:{kind:'attack-stance'}}}];target(t);prompts=[{regular:'15'}];await usePower(a,'starter:counterstrike-technique');assert.equal(a.system.lifepool.focus.value,25);assert.equal(t.system.lifepool.health.value,92);});
test('Combat Support enforces once per combat and applies only to an ally',async()=>{setup();const a=actor('hero',['inspiration','change-of-plans','combat-support']),t=actor('ally');game.combat.turns=[{actor:a}];target(t);prompts=[{}];await usePower(a,'starter:combat-support');assert.equal(a.system.lifepool.focus.value,20);assert.equal(t.effects[0].flags[ID].sourceActor,a.uuid);t.effects=[];await assert.rejects(usePower(a,'starter:combat-support'),/already been used/);});
test('Sniping rejects short distance before spending or rolling',async()=>{setup();const a=actor('hero',['sniping']),t=actor('enemy');target(t);prompts=[{distance:'19'}];await assert.rejects(usePower(a,'starter:sniping'),/Distance/);assert.equal(a.system.lifepool.focus.value,30);assert.equal(messages.length,0);});
test('cancelling native attack roll does not charge Focus',async()=>{setup();const a=actor('hero',['sniping']);target(actor('enemy'));prompts=[{distance:'20'}];rollCancelled=true;await usePower(a,'starter:sniping');assert.equal(a.system.lifepool.focus.value,30);assert.equal(messages.length,0);});
test('Sniping waits for GM outcome, applies triple damage, and blocks replay',async()=>{setup();const a=actor('hero',['sniping']),t=actor('enemy');target(t);prompts=[{distance:'20'}];const m=await usePower(a,'starter:sniping');assert.equal(a.system.lifepool.focus.value,25);assert.equal(t.system.lifepool.health.value,100);prompts=[{defense0:'13',dr0:'0',final:true}];await resolveAttack(m);assert.equal(t.system.lifepool.health.value,37);await assert.rejects(resolveAttack(m),/already/);assert.equal(t.system.lifepool.health.value,37);});
test('Snap Shooting applies bleeding and ends Defense Stance on a hit',async()=>{setup();const a=actor('hero',['snap-shooting']),t=actor('enemy');t.effects=[{id:'stance',flags:{[ID]:{kind:'defense-stance'}}}];target(t);prompts=[{}];const m=await usePower(a,'starter:snap-shooting');prompts=[{defense0:'13',dr0:'0',final:true}];await resolveAttack(m);assert.equal(t.system.lifepool.health.value,79);assert.deepEqual(t.effects.map(e=>e.flags[ID].kind),['bleeding']);});
test('target write failure locks outcome against accidental reapplication',async()=>{setup();const a=actor('hero',['sniping']),t=actor('enemy');target(t);prompts=[{distance:'20'}];const m=await usePower(a,'starter:sniping');t.update=async()=>{throw Error('Offline');};prompts=[{defense0:'13',dr0:'0',final:true}];await assert.rejects(resolveAttack(m),/Partial outcome/);assert.equal(m.flags[ID].resolutionState,'error-review-required');await assert.rejects(resolveAttack(m),/recovery/);});
test('players and secondary GMs cannot mutate power effects',async()=>{setup();const a=actor('hero',['attack-stance']);game.user.isGM=false;await assert.rejects(usePower(a,'starter:attack-stance'),/GM/);game.user.isGM=true;game.users.activeGM.id='other';await assert.rejects(usePower(a,'starter:attack-stance'),/resolution GM/);assert.equal(a.effects.length,0);});
test('Change of Plans adjusts unresolved trouble and prevents duplicate charge',async()=>{setup();const a=actor('hero',['inspiration','change-of-plans']),ally=actor('ally');const roll=new FakeRoll('',{},{actor:ally,rollType:'nonCombat',ability:'ego',edges:0,troubles:1});const m=await ChatMessage.create({rolls:[roll]});prompts=[{message:m.id}];await usePower(a,'starter:change-of-plans');assert.equal(roll.edges,1);assert.equal(a.system.lifepool.focus.value,25);prompts=[{message:m.id}];await assert.rejects(usePower(a,'starter:change-of-plans'),/already used/);assert.equal(a.system.lifepool.focus.value,25);});
test('Fearless and Combat Support are included in ability rolls',async()=>{setup();const a=actor('hero',['fearless']);a.effects=[{flags:{[ID]:{kind:'combat-support'}}}];prompts=[{tn:'15',fear:true}];const m=await abilityCheck(a,'ego');assert.equal(m.rolls[0].edges,1);assert.equal(m.rolls[0].dice[1].results[0].result,1);assert.equal(m.rolls[0].options[ID].protectedMiddle,true);});
test('content upgrade creates recovery and preserves customized name and effects',async()=>{setup();const a=actor('hero',['sniping']);a.items[0].name='Custom name';a.items[0].effects=[{name:'custom'}];prompts=[true];await upgradeContent(a);assert.equal(backups.length,1);assert.equal(a.items[0].name,'Custom name');assert.deepEqual(a.items[0].effects,[{name:'custom'}]);assert.match(a.items[0].system.description,/triple damage/);assert.equal(a.system.lifepool.focus.value,30);});
test('reroll wrapper protects Combat Support and locks resolved attacks',async()=>{setup();registerActionHooks();const a=actor('hero'),roll=new FakeRoll('',{},{actor:a,edges:0,troubles:1,[ID]:{protectedMiddle:true}}),m=doc({flags:{}});await roll.mvReroll('dieM',m);assert.equal(roll.rerolls.history.length,0);await roll.mvReroll('die1',m);assert.equal(roll.rerolls.history.length,1);m.flags[ID]={resolved:true};await roll.undoLastReroll(m);assert.equal(roll.rerolls.history.length,1);});
